"""
Generates a downloadable PDF medical report summarizing a prediction (or
a patient's recent history) for the patient to save or share with their
doctor. Built with ReportLab — a real, complete PDF, not a stub.
"""
from __future__ import annotations

import html
import json
from datetime import datetime, timezone
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.core.config import settings
from app.models.prediction import Prediction
from app.models.user import User

DISCLAIMER = (
    "This report was generated by MedVision AI, an artificial intelligence assistant. "
    "It provides general educational information only and is NOT a medical diagnosis. "
    "It does not replace evaluation by a licensed physician. If you are experiencing a "
    "medical emergency, seek immediate in-person care."
)


def generate_prediction_report_pdf(user: User, prediction: Prediction) -> str:
    output_dir = Path(settings.UPLOAD_DIR) / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"report_{prediction.id}.pdf"

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleCustom", parent=styles["Title"], textColor=colors.HexColor("#0F766E"))
    heading_style = ParagraphStyle("HeadingCustom", parent=styles["Heading2"], textColor=colors.HexColor("#0F766E"))
    body_style = styles["BodyText"]
    disclaimer_style = ParagraphStyle(
        "Disclaimer", parent=styles["BodyText"], textColor=colors.HexColor("#B91C1C"), fontSize=9
    )

    doc = SimpleDocTemplate(
        str(output_path), pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm, leftMargin=2 * cm, rightMargin=2 * cm
    )

    story = []
    story.append(Paragraph("MedVision AI — Health Report", title_style))
    story.append(Spacer(1, 4))
    story.append(Paragraph(f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", body_style))
    story.append(Paragraph(html.escape(f"Patient: {user.full_name} ({user.email})"), body_style))
    story.append(Spacer(1, 12))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#0F766E")))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Reported Symptoms / Input", heading_style))
    story.append(Paragraph(html.escape(prediction.input_summary or "—"), body_style))
    story.append(Spacer(1, 12))

    story.append(Paragraph("AI-Generated Analysis", heading_style))
    results = json.loads(prediction.results_json or "[]")
    if results:
        table_data = [["Possible Condition", "Probability", "Risk Level", "Recommended Specialist"]]
        for item in results:
            table_data.append(
                [
                    html.escape(item.get("disease_name", "—")),
                    f"{round(item.get('probability', 0) * 100)}%",
                    html.escape(str(item.get("risk_level", "—"))).capitalize(),
                    html.escape(item.get("recommended_specialist") or "—"),
                ]
            )
        table = Table(table_data, colWidths=[6 * cm, 2.5 * cm, 3 * cm, 5 * cm])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F766E")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F1F5F9")]),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )
        story.append(table)
        story.append(Spacer(1, 12))

        for item in results[:1]:
            story.append(Paragraph(html.escape(f"Top Possibility: {item.get('disease_name')}"), heading_style))
            story.append(Paragraph(html.escape(item.get("explanation", "")), body_style))
            if item.get("home_care_tips"):
                story.append(Paragraph(f"<b>Home care:</b> {html.escape(item['home_care_tips'])}", body_style))
            if item.get("foods_to_eat"):
                story.append(Paragraph(f"<b>Foods to eat:</b> {html.escape(item['foods_to_eat'])}", body_style))
            if item.get("foods_to_avoid"):
                story.append(Paragraph(f"<b>Foods to avoid:</b> {html.escape(item['foods_to_avoid'])}", body_style))
            if item.get("when_to_visit_hospital"):
                story.append(
                    Paragraph(f"<b>When to seek care:</b> {html.escape(item['when_to_visit_hospital'])}", body_style)
                )
    else:
        story.append(Paragraph("No specific conditions were identified from this input.", body_style))

    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#CBD5E1")))
    story.append(Spacer(1, 8))
    story.append(Paragraph(DISCLAIMER, disclaimer_style))

    doc.build(story)
    return str(output_path)
