"""add startup features: family, care, appointments, health tracking, emergency, platform

Revision ID: 04465b9f6b92
Revises: 9986a692ce2f
Create Date: 2026-06-21 17:28:54.526032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04465b9f6b92'
down_revision: Union[str, Sequence[str], None] = '9986a692ce2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('specialties', sa.String(length=400), nullable=True),
    sa.Column('has_emergency_room', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pharmacies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_24h', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('hashed_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requests_per_minute', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('care_connections',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'ENDED', name='connectionstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_connections_doctor_id'), 'care_connections', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_care_connections_patient_id'), 'care_connections', ['patient_id'], unique=False)
    op.create_table('direct_conversations',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direct_conversations_doctor_id'), 'direct_conversations', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_direct_conversations_patient_id'), 'direct_conversations', ['patient_id'], unique=False)
    op.create_table('doctor_time_slots',
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_time_slots_doctor_id'), 'doctor_time_slots', ['doctor_id'], unique=False)
    op.create_table('emergency_alerts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('notified_contacts_json', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_alerts_user_id'), 'emergency_alerts', ['user_id'], unique=False)
    op.create_table('emergency_contacts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contacts_user_id'), 'emergency_contacts', ['user_id'], unique=False)
    op.create_table('family_members',
    sa.Column('guardian_user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('chronic_conditions', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guardian_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_members_guardian_user_id'), 'family_members', ['guardian_user_id'], unique=False)
    op.create_table('patient_medications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('medication_name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('frequency_per_day', sa.Integer(), nullable=False),
    sa.Column('reminder_times', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_medications_user_id'), 'patient_medications', ['user_id'], unique=False)
    op.create_table('referral_codes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_referral_codes_code'), 'referral_codes', ['code'], unique=True)
    op.create_table('referrals',
    sa.Column('referrer_id', sa.String(length=36), nullable=False),
    sa.Column('referred_user_id', sa.String(length=36), nullable=False),
    sa.Column('reward_granted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_user_id')
    )
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'PREMIUM', name='subscriptiontier'), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('symptom_diary_entries',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('pain_level', sa.Integer(), nullable=True),
    sa.Column('symptoms_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_diary_entries_entry_date'), 'symptom_diary_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_symptom_diary_entries_user_id'), 'symptom_diary_entries', ['user_id'], unique=False)
    op.create_table('two_factor_auth',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('backup_codes_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('usage_counters',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('chat_messages_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_counters_usage_date'), 'usage_counters', ['usage_date'], unique=False)
    op.create_index(op.f('ix_usage_counters_user_id'), 'usage_counters', ['user_id'], unique=False)
    op.create_table('vaccinations',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('vaccine_name', sa.String(length=150), nullable=False),
    sa.Column('dose_number', sa.Integer(), nullable=False),
    sa.Column('date_administered', sa.Date(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('administered_at', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccinations_user_id'), 'vaccinations', ['user_id'], unique=False)
    op.create_table('wearable_data_points',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('metric_type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wearable_data_points_recorded_date'), 'wearable_data_points', ['recorded_date'], unique=False)
    op.create_index(op.f('ix_wearable_data_points_user_id'), 'wearable_data_points', ['user_id'], unique=False)
    op.create_table('appointments',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('slot_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='appointmentstatus'), nullable=False),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['doctor_time_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_table('direct_messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['direct_conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direct_messages_conversation_id'), 'direct_messages', ['conversation_id'], unique=False)
    op.create_table('medication_logs',
    sa.Column('patient_medication_id', sa.String(length=36), nullable=False),
    sa.Column('taken_at', sa.Date(), nullable=False),
    sa.Column('was_taken', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_medication_id'], ['patient_medications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_logs_patient_medication_id'), 'medication_logs', ['patient_medication_id'], unique=False)
    op.add_column('predictions', sa.Column('family_member_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_predictions_family_member_id'), 'predictions', ['family_member_id'], unique=False)
    op.create_foreign_key(None, 'predictions', 'family_members', ['family_member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.drop_index(op.f('ix_predictions_family_member_id'), table_name='predictions')
    op.drop_column('predictions', 'family_member_id')
    op.drop_index(op.f('ix_medication_logs_patient_medication_id'), table_name='medication_logs')
    op.drop_table('medication_logs')
    op.drop_index(op.f('ix_direct_messages_conversation_id'), table_name='direct_messages')
    op.drop_table('direct_messages')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_wearable_data_points_user_id'), table_name='wearable_data_points')
    op.drop_index(op.f('ix_wearable_data_points_recorded_date'), table_name='wearable_data_points')
    op.drop_table('wearable_data_points')
    op.drop_index(op.f('ix_vaccinations_user_id'), table_name='vaccinations')
    op.drop_table('vaccinations')
    op.drop_index(op.f('ix_usage_counters_user_id'), table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_usage_date'), table_name='usage_counters')
    op.drop_table('usage_counters')
    op.drop_table('two_factor_auth')
    op.drop_index(op.f('ix_symptom_diary_entries_user_id'), table_name='symptom_diary_entries')
    op.drop_index(op.f('ix_symptom_diary_entries_entry_date'), table_name='symptom_diary_entries')
    op.drop_table('symptom_diary_entries')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_referral_codes_code'), table_name='referral_codes')
    op.drop_table('referral_codes')
    op.drop_index(op.f('ix_patient_medications_user_id'), table_name='patient_medications')
    op.drop_table('patient_medications')
    op.drop_index(op.f('ix_family_members_guardian_user_id'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_emergency_contacts_user_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_emergency_alerts_user_id'), table_name='emergency_alerts')
    op.drop_table('emergency_alerts')
    op.drop_index(op.f('ix_doctor_time_slots_doctor_id'), table_name='doctor_time_slots')
    op.drop_table('doctor_time_slots')
    op.drop_index(op.f('ix_direct_conversations_patient_id'), table_name='direct_conversations')
    op.drop_index(op.f('ix_direct_conversations_doctor_id'), table_name='direct_conversations')
    op.drop_table('direct_conversations')
    op.drop_index(op.f('ix_care_connections_patient_id'), table_name='care_connections')
    op.drop_index(op.f('ix_care_connections_doctor_id'), table_name='care_connections')
    op.drop_table('care_connections')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('pharmacies')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
