"""initial schema

Revision ID: 9986a692ce2f
Revises: 
Create Date: 2026-06-20 12:24:12.424592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9986a692ce2f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('alternative_names', sa.Text(), nullable=True),
    sa.Column('icd_code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('causes', sa.Text(), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('stages', sa.Text(), nullable=True),
    sa.Column('complications', sa.Text(), nullable=True),
    sa.Column('treatment_overview', sa.Text(), nullable=True),
    sa.Column('prevention', sa.Text(), nullable=True),
    sa.Column('nutrition_advice', sa.Text(), nullable=True),
    sa.Column('foods_to_eat', sa.Text(), nullable=True),
    sa.Column('foods_to_avoid', sa.Text(), nullable=True),
    sa.Column('lifestyle_advice', sa.Text(), nullable=True),
    sa.Column('recommended_specialist', sa.String(length=150), nullable=True),
    sa.Column('emergency_warning_signs', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=400), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('avg_recovery_days', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diseases_icd_code'), 'diseases', ['icd_code'], unique=False)
    op.create_index(op.f('ix_diseases_name'), 'diseases', ['name'], unique=True)
    op.create_table('knowledge_chunks',
    sa.Column('source_type', sa.Enum('DISEASE', 'SYMPTOM', 'MEDICATION', 'ARTICLE', 'VERIFIED_CASE', name='knowledgesourcetype'), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('vector_position', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_source_id'), 'knowledge_chunks', ['source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_source_type'), 'knowledge_chunks', ['source_type'], unique=False)
    op.create_table('medical_articles',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('file_type', sa.Enum('PDF', 'DOCX', 'MARKDOWN', 'TEXT', name='articlefiletype'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=400), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medications',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active_ingredient', sa.String(length=200), nullable=True),
    sa.Column('drug_category', sa.String(length=150), nullable=True),
    sa.Column('general_indications', sa.Text(), nullable=True),
    sa.Column('contraindications', sa.Text(), nullable=True),
    sa.Column('possible_side_effects', sa.Text(), nullable=True),
    sa.Column('drug_interactions', sa.Text(), nullable=True),
    sa.Column('age_restrictions', sa.Text(), nullable=True),
    sa.Column('pregnancy_considerations', sa.Text(), nullable=True),
    sa.Column('storage_information', sa.Text(), nullable=True),
    sa.Column('educational_notes', sa.Text(), nullable=True),
    sa.Column('prescription_required', sa.Boolean(), nullable=False),
    sa.Column('linked_disease_tags', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_name'), 'medications', ['name'], unique=True)
    op.create_table('symptoms',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('body_system', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptoms_name'), 'symptoms', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DOCTOR', 'PATIENT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('dark_mode', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('chat_conversations',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversations_user_id'), 'chat_conversations', ['user_id'], unique=False)
    op.create_table('disease_symptoms',
    sa.Column('disease_id', sa.String(length=36), nullable=False),
    sa.Column('symptom_id', sa.String(length=36), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_symptoms_disease_id'), 'disease_symptoms', ['disease_id'], unique=False)
    op.create_index(op.f('ix_disease_symptoms_symptom_id'), 'disease_symptoms', ['symptom_id'], unique=False)
    op.create_table('doctors',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('license_number', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('image_records',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('body_part', sa.Enum('SKIN', 'EYE', 'TONGUE', 'NAILS', 'THROAT', 'WOUND', 'OTHER', name='imagebodypart'), nullable=False),
    sa.Column('quality_ok', sa.Boolean(), nullable=False),
    sa.Column('quality_note', sa.String(length=300), nullable=True),
    sa.Column('predicted_disease', sa.String(length=200), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('series_id', sa.String(length=36), nullable=True),
    sa.Column('verified_label', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('expert_approved_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expert_approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_records_series_id'), 'image_records', ['series_id'], unique=False)
    op.create_index(op.f('ix_image_records_user_id'), 'image_records', ['user_id'], unique=False)
    op.create_table('lab_reports',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('extracted_values_json', sa.Text(), nullable=True),
    sa.Column('abnormal_findings_json', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_reports_user_id'), 'lab_reports', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('chronic_conditions', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('sleep_hours_avg', sa.Float(), nullable=True),
    sa.Column('water_intake_liters_avg', sa.Float(), nullable=True),
    sa.Column('exercise_minutes_per_week', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('predictions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.Enum('TEXT', 'VOICE', 'IMAGE', 'LAB_REPORT', name='predictionsource'), nullable=False),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=False),
    sa.Column('results_json', sa.Text(), nullable=False),
    sa.Column('top_disease', sa.String(length=200), nullable=True),
    sa.Column('top_probability', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'EMERGENCY', name='risklevel'), nullable=False),
    sa.Column('recommended_specialist', sa.String(length=150), nullable=True),
    sa.Column('recovery_estimate_days', sa.Integer(), nullable=True),
    sa.Column('detected_symptoms_json', sa.Text(), nullable=True),
    sa.Column('feature_importance_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_user_id'), 'predictions', ['user_id'], unique=False)
    op.create_table('voice_records',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('extracted_symptoms', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_label', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_records_user_id'), 'voice_records', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='chatrole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('retrieved_context_json', sa.Text(), nullable=True),
    sa.Column('used_fallback', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_table('medical_history',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('health_score_snapshot', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_history_user_id'), 'medical_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_history_user_id'), table_name='medical_history')
    op.drop_table('medical_history')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_voice_records_user_id'), table_name='voice_records')
    op.drop_table('voice_records')
    op.drop_index(op.f('ix_predictions_user_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('patients')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_lab_reports_user_id'), table_name='lab_reports')
    op.drop_table('lab_reports')
    op.drop_index(op.f('ix_image_records_user_id'), table_name='image_records')
    op.drop_index(op.f('ix_image_records_series_id'), table_name='image_records')
    op.drop_table('image_records')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_disease_symptoms_symptom_id'), table_name='disease_symptoms')
    op.drop_index(op.f('ix_disease_symptoms_disease_id'), table_name='disease_symptoms')
    op.drop_table('disease_symptoms')
    op.drop_index(op.f('ix_chat_conversations_user_id'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_symptoms_name'), table_name='symptoms')
    op.drop_table('symptoms')
    op.drop_index(op.f('ix_medications_name'), table_name='medications')
    op.drop_table('medications')
    op.drop_table('medical_articles')
    op.drop_index(op.f('ix_knowledge_chunks_source_type'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_source_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_diseases_name'), table_name='diseases')
    op.drop_index(op.f('ix_diseases_icd_code'), table_name='diseases')
    op.drop_table('diseases')
    # ### end Alembic commands ###
